// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {boolean} isLike
 * @param {string} selector - 选择器  https://developer.mozilla.org/zh-CN/docs/Web/API/Document_Object_Model/Locating_DOM_elements_using_selectors
 * @returns {Promise.<void>}
 */
export async function JavaScript_action_Like(isLike, selector) {
	// BEGIN USER CODE
	let ele = document.querySelector(selector);
	if (ele) {
		ele.classList.remove('heartAnimation');
		if (isLike) {
			setTimeout(() => {
				ele.classList.add('heartAnimation');
			}, 10);
		}
	}
	// END USER CODE
}
